os: linux
dist: xenial
language: ruby
cache: bundler
jobs:
  include:
    - rvm: 2.5.3
      before_install:
        - wget https://repo.mysql.com/mysql-apt-config_0.8.15-1_all.deb
        - sudo dpkg -i mysql-apt-config_*.deb
        - sudo apt-get -q update
        - sudo apt-get -q install unixodbc unixodbc-dev mysql-connector-odbc mysql-client
      env:
        - DB=mysql
        - CONN_STR='DRIVER=MySQL;SERVER=localhost;DATABASE=odbc_test;USER=root;PASSWORD=;'
    - rvm: 2.5.3
      env:
        - DB=postgresql
        - CONN_STR='DRIVER={PostgreSQL ANSI};SERVER=localhost;PORT=5432;DATABASE=odbc_test;UID=postgres;'
      services:
        - postgresql
      addons:
        apt:
          packages:
            - unixodbc
            - unixodbc-dev
            - odbc-postgresql
before_script: bin/ci-setup
