sudo: required
language: ruby
cache: bundler
before_install:
- wget https://repo.mysql.com/mysql-apt-config_0.8.15-1_all.deb
- sudo dpkg -i mysql-apt-config_*.deb
matrix:
  include:
  - rvm: 2.5.1
    env:
    - DB=mysql
    - CONN_STR='DRIVER=MySQL;SERVER=localhost;DATABASE=odbc_test;USER=root;PASSWORD=;'
    addons:
      mysql: "5.5"
      apt:
        update: true
        packages:
        - unixodbc
        - unixodbc-dev
        - mysql-connector-odbc
        - mysql-client
  - rvm: 2.5.1
    env:
    - DB=postgresql
    - CONN_STR='DRIVER={PostgreSQL ANSI};SERVER=localhost;PORT=5432;DATABASE=odbc_test;UID=postgres;'
    services:
      - postgresql
    addons:
      apt:
        packages:
        - unixodbc
        - unixodbc-dev
        - odbc-postgresql
before_script: bin/ci-setup
